@startuml
abstract class AbstractUdpCommunicator {
    <<const>> POLL_TIMEOUT_MS : int = 1000
    + AbstractUdpCommunicator(udpClient:Utils.Network.UdpClient)
    + Send(message:Google.Protobuf.IMessage) : void
}
class "ConcurrentQueue`1"<T> {
}
BaseThread <|-- AbstractUdpCommunicator
AbstractUdpCommunicator --> "MessagesQueue<Any>" "ConcurrentQueue`1"
@enduml
