@startuml
class ClientCommunicator {
    <<const>> POLL_TIMEOUT_MS : int = 1000
    + ClientCommunicator(ipAddress:string, port:int)
    + Send(message:Google.Protobuf.IMessage) : void
}
class "SynchronizedCollection`1"<T> {
}
BaseThread <|-- ClientCommunicator
ClientCommunicator --> "Clients<ClientDetails>" "SynchronizedCollection`1"
@enduml
