@startuml
!include .\\Scripts\Game\ClientManager.puml
!include .\\Scripts\Game\HostManager.puml
!include .\\Scripts\Game\Initializer.puml
!include .\\Scripts\General\ClientDetails.puml
!include .\\Scripts\General\GameManager.puml
!include .\\Scripts\General\TcpClientCommunicator.puml
!include .\\Scripts\General\TcpServerCommunicator.puml
!include .\\Scripts\General\UdpCommunicator.puml
!include .\\Scripts\General\UdpServerCommunicator.puml
!include .\\Scripts\MainMenu\ClientManager.puml
!include .\\Scripts\MainMenu\Exceptions.puml
!include .\\Scripts\MainMenu\HostManager.puml
!include .\\Scripts\MainMenu\MainMenuController.puml
!include .\\Scripts\Messages\Base.puml
!include .\\Scripts\Messages\MainMenu.puml
!include .\\Scripts\Utils\BaseThread.puml
!include .\\Scripts\Utils\Messages.puml
!include .\\Scripts\Utils\Network\Exceptions.puml
!include .\\Scripts\Utils\UI\General.puml
!include .\\Scripts\Utils\UI\ScrollView.puml
!include .\\Scripts\Utils\Network\TCP\TcpClient.puml
!include .\\Scripts\Utils\Network\TCP\TcpServer.puml
!include .\\Scripts\Utils\Network\UDP\UdpClient.puml
@enduml
